const $=id=>document.getElementById(id); $('apiKey').value=localStorage.getItem('openaudit_api_key')||'';function saveKey(){localStorage.setItem('openaudit_api_key',$('apiKey').value)}function headers(){const h={'Content-Type':'application/json'}; const k=$('apiKey').value; if(k)h['X-API-Key']=k; return h}async function api(url,opt={}){opt.headers={...headers(),...(opt.headers||{})}; const r=await fetch(url,opt); const t=await r.text(); if(!r.ok){$('error').textContent=t; throw new Error(t)}; $('error').textContent=''; return t?JSON.parse(t):{}}async function auditText(){ $('auditResult').textContent=JSON.stringify(await api('/audit/text',{method:'POST',body:JSON.stringify({text:$('text').value,options:{max_hits:20}})}),null,2)}async function loadConfig(){ $('config').textContent=JSON.stringify(await api('/config'),null,2)}async function loadRules(){ const data=await api('/rules?q='+encodeURIComponent($('ruleQ').value)); $('rules').innerHTML=data.items.map(r=>`<div><button onclick="detail('${r.id}')">${r.id}</button> ${r.type} ${r.category} ${r.action} <button onclick="toggleRule('${r.id}',${!r.enabled})">toggle</button> <button onclick="delRule('${r.id}')">delete</button></div>`).join('')}async function detail(id){$('ruleDetail').textContent=JSON.stringify(await api('/rules/'+id),null,2)}async function createRule(){const id=$('newId').value, kws=$('newWords').value.split(',').map(s=>s.trim()).filter(Boolean); await api('/rules/create',{method:'POST',body:JSON.stringify({rule:{id,type:'keyword',category:'custom',risk_level:'medium',action:'review',score:60,enabled:true,keywords:kws}})}); await loadRules()}async function toggleRule(id,en){await api('/rules/update/'+id,{method:'PATCH',body:JSON.stringify({patch:{enabled:en}})}); await loadRules()}async function delRule(id){await api('/rules/delete/'+id,{method:'DELETE'}); await loadRules()}async function loadStats(){$('stats').textContent=JSON.stringify(await api('/logs/stats'),null,2)}async function loadLogs(){$('logs').textContent=JSON.stringify(await api('/logs/recent?limit=20'),null,2)}loadConfig();loadRules().catch(()=>{});

async function loadHistory(){const q=new URLSearchParams(); for (const [id,k] of [['histRule','rule_id'],['histAction','action'],['histActor','actor'],['histSource','source'],['histBatch','import_batch_id']]){const v=$(id).value;if(v)q.set(k,v)} const data=await api('/rules/history?'+q.toString()); $('history').innerHTML=data.items.map(x=>`<div><button onclick="showChange('${x.change_id}')">${x.change_id}</button> ${x.timestamp} ${x.action} ${x.rule_id||''} ${x.actor||''} <button onclick="showDiff('${x.rule_id||''}')">diff</button> <button onclick="rollbackChange('${x.rule_id||''}','${x.change_id}')">rollback</button></div>`).join('')}
async function showChange(id){$('historyDetail').textContent=JSON.stringify(await api('/rules/history/'+id),null,2)}
async function showDiff(id){if(!id){$('historyDiff').textContent='No rule id for this change';return} $('historyDiff').textContent=JSON.stringify(await api('/rules/'+id+'/diff'),null,2)}
async function rollbackChange(rule,change){if(!rule){alert('Rollback requires a rule id');return} if(!confirm('Rollback '+rule+' to before '+change+'?'))return; try{$('historyDetail').textContent=JSON.stringify(await api('/rules/rollback/'+rule,{method:'POST',body:JSON.stringify({change_id:change,note:'admin rollback'})}),null,2); await loadHistory(); await loadRules()}catch(e){$('historyDetail').textContent=e.message}}
async function loadBatches(){const data=await api('/imports/batches'); $('batches').innerHTML=data.items.map(x=>`<div><button onclick="showBatch('${x.batch_id}')">${x.batch_id}</button> ${x.timestamp} ${x.source} ${x.status} files=${x.files_scanned} read=${x.keywords_read} dedup=${x.keywords_deduplicated}</div>`).join('')}
async function showBatch(id){$('batchDetail').textContent=JSON.stringify(await api('/imports/batches/'+id),null,2)}
loadHistory().catch(()=>{});loadBatches().catch(()=>{});
function importPayload(){return {input_path:$('impInput').value,output_path:$('impOutput').value,source:$('impSource').value||'sensitive-lexicon',type:$('impType').value,category:$('impCategory').value,risk_level:$('impRisk').value||'medium',action:$('impAction').value||'review',strict:$('impStrict').checked,reload_after_import:$('impReload').checked,record_history:true}}
async function importPreview(){$('importResult').textContent=JSON.stringify(await api('/imports/preview',{method:'POST',body:JSON.stringify(importPayload())}),null,2)}
async function runImport(){$('importResult').textContent=JSON.stringify(await api('/imports/run',{method:'POST',body:JSON.stringify(importPayload())}),null,2)}
