const $=id=>document.getElementById(id); $('apiKey').value=localStorage.getItem('openaudit_api_key')||'';function saveKey(){localStorage.setItem('openaudit_api_key',$('apiKey').value)}function headers(){const h={'Content-Type':'application/json'}; const k=$('apiKey').value; if(k)h['X-API-Key']=k; return h}async function api(url,opt={}){opt.headers={...headers(),...(opt.headers||{})}; const r=await fetch(url,opt); const t=await r.text(); if(!r.ok){$('error').textContent=t; throw new Error(t)}; $('error').textContent=''; return t?JSON.parse(t):{}}function renderAuditResult(res){const rows=(res.hits||[]).map(h=>`${h.rule_id} ${h.type}${h.variant_type?'/'+h.variant_type:''} score=${h.score} risk=${h.risk_level} action=${h.action} match=${h.match}${h.explanation?'\n  '+h.explanation:''}`).join('\n'); $('auditResult').textContent=`decision=${res.action} score=${res.risk_score} matched=${res.matched}\n${rows}\n\n${JSON.stringify(res,null,2)}`}async function auditText(){ renderAuditResult(await api('/audit/text',{method:'POST',body:JSON.stringify({text:$('text').value,options:{max_hits:20}})}))}async function loadConfig(){ $('config').textContent=JSON.stringify(await api('/config'),null,2)}async function loadRules(){ const data=await api('/rules?q='+encodeURIComponent($('ruleQ').value)); $('rules').innerHTML=data.items.map(r=>`<div><button onclick="detail('${r.id}')">${r.id}</button> ${r.type} ${r.category} ${r.action} ${r.variant&&r.variant.enabled?'variant':''} <button onclick="toggleRule('${r.id}',${!r.enabled})">toggle</button> <button onclick="delRule('${r.id}')">delete</button></div>`).join('')}async function detail(id){$('ruleDetail').textContent=JSON.stringify(await api('/rules/'+id),null,2)}async function createRule(){const id=$('newId').value, kws=$('newWords').value.split(',').map(s=>s.trim()).filter(Boolean); await api('/rules/create',{method:'POST',body:JSON.stringify({rule:{id,type:'keyword',category:'custom',risk_level:'medium',action:'review',score:60,enabled:true,keywords:kws}})}); await loadRules()}async function toggleRule(id,en){await api('/rules/update/'+id,{method:'PATCH',body:JSON.stringify({patch:{enabled:en}})}); await loadRules()}async function delRule(id){await api('/rules/delete/'+id,{method:'DELETE'}); await loadRules()}async function loadStats(){$('stats').textContent=JSON.stringify(await api('/logs/stats'),null,2)}async function loadLogs(){$('logs').textContent=JSON.stringify(await api('/logs/recent?limit=20'),null,2)}loadConfig();loadRules().catch(()=>{});

async function loadHistory(){const q=new URLSearchParams(); for (const [id,k] of [['histRule','rule_id'],['histAction','action'],['histActor','actor'],['histSource','source'],['histBatch','import_batch_id']]){const v=$(id).value;if(v)q.set(k,v)} const data=await api('/rules/history?'+q.toString()); $('history').innerHTML=data.items.map(x=>`<div><button onclick="showChange('${x.change_id}')">${x.change_id}</button> ${x.timestamp} ${x.action} ${x.rule_id||''} ${x.actor||''} <button onclick="showDiff('${x.rule_id||''}')">diff</button> <button onclick="rollbackChange('${x.rule_id||''}','${x.change_id}')">rollback</button></div>`).join('')}
async function showChange(id){$('historyDetail').textContent=JSON.stringify(await api('/rules/history/'+id),null,2)}
async function showDiff(id){if(!id){$('historyDiff').textContent='No rule id for this change';return} $('historyDiff').textContent=JSON.stringify(await api('/rules/'+id+'/diff'),null,2)}
async function rollbackChange(rule,change){if(!rule){alert('Rollback requires a rule id');return} if(!confirm('Rollback '+rule+' to before '+change+'?'))return; try{$('historyDetail').textContent=JSON.stringify(await api('/rules/rollback/'+rule,{method:'POST',body:JSON.stringify({change_id:change,note:'admin rollback'})}),null,2); await loadHistory(); await loadRules()}catch(e){$('historyDetail').textContent=e.message}}
async function loadBatches(){const data=await api('/imports/batches'); $('batches').innerHTML=data.items.map(x=>`<div><button onclick="showBatch('${x.batch_id}')">${x.batch_id}</button> ${x.timestamp} ${x.source} ${x.status} files=${x.files_scanned} read=${x.keywords_read} dedup=${x.keywords_deduplicated} <button onclick="rollbackBatch('${x.batch_id}')">rollback</button></div>`).join('')}
async function showBatch(id){$('batchDetail').textContent=JSON.stringify(await api('/imports/batches/'+id),null,2)}
loadHistory().catch(()=>{});loadBatches().catch(()=>{});
function importPayload(){return {input_path:$('impInput').value,output_path:$('impOutput').value,source:$('impSource').value||'sensitive-lexicon',type:$('impType').value,category:$('impCategory').value,risk_level:$('impRisk').value||'medium',action:$('impAction').value||'review',strict:$('impStrict').checked,reload_after_import:$('impReload').checked,record_history:true}}
async function importPreview(){$('importResult').textContent=JSON.stringify(await api('/imports/preview',{method:'POST',body:JSON.stringify(importPayload())}),null,2)}
async function runImport(){$('importResult').textContent=JSON.stringify(await api('/imports/run',{method:'POST',body:JSON.stringify(importPayload())}),null,2)}
async function createDraft(){const id=$('draftId').value, kws=$('draftWords').value.split(',').map(s=>s.trim()).filter(Boolean); $('releaseResult').textContent=JSON.stringify(await api('/rules/drafts',{method:'POST',body:JSON.stringify({rule:{id,type:'keyword',category:'custom',risk_level:'medium',action:'review',score:60,keywords:kws}})}),null,2); await loadDrafts()}
async function loadDrafts(){const data=await api('/rules/drafts'); $('drafts').innerHTML=data.items.map(r=>`<div><button onclick="stageDraft('${r.id}')">stage</button> ${r.id} ${r.type} ${r.category}</div>`).join('')}
async function stageDraft(id){$('releaseResult').textContent=JSON.stringify(await api('/rules/drafts/'+id+'/stage',{method:'POST'}),null,2); await loadDrafts(); await loadStaged()}
async function loadStaged(){const data=await api('/rules/staged'); $('staged').innerHTML=data.items.map(r=>`<div>${r.id} ${r.type} ${r.category}</div>`).join('')}
async function publishStaged(){$('releaseResult').textContent=JSON.stringify(await api('/rules/publish',{method:'POST',body:JSON.stringify({sample_text:$('simulateText').value})}),null,2); await loadRules(); await loadStaged(); await loadReleases()}
async function loadReleases(){const data=await api('/rules/releases'); $('releases').innerHTML=(data.items||[]).map(r=>`<div><button onclick="showRelease('${r.version}')">${r.version}</button> ${r.status} rules=${r.rule_count} <button onclick="rollbackRelease('${r.version}')">rollback</button></div>`).join('')}
async function showRelease(v){$('releaseResult').textContent=JSON.stringify(await api('/rules/releases/'+v),null,2)}
async function rollbackRelease(v){if(!confirm('Rollback ruleset to '+v+'?'))return; $('releaseResult').textContent=JSON.stringify(await api('/rules/releases/'+v+'/rollback',{method:'POST'}),null,2); await loadRules(); await loadReleases()}
async function detectConflicts(){$('releaseResult').textContent=JSON.stringify(await api('/rules/conflicts',{method:'POST'}),null,2)}
async function simulateRules(){$('releaseResult').textContent=JSON.stringify(await api('/rules/simulate',{method:'POST',body:JSON.stringify({text:$('simulateText').value,scope:$('simulateScope').value,max_hits:20})}),null,2)}
async function bulkDisableCustom(){await api('/rules/bulk/disable',{method:'POST',body:JSON.stringify({category:'custom',state:'published'})}); await loadRules()}
async function bulkEnableCustom(){await api('/rules/bulk/enable',{method:'POST',body:JSON.stringify({category:'custom',state:'published'})}); await loadRules()}
async function rollbackBatch(id){if(!confirm('Rollback import batch '+id+'?'))return; $('batchDetail').textContent=JSON.stringify(await api('/imports/batches/'+id+'/rollback',{method:'POST'}),null,2); await loadBatches(); await loadRules()}
